<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "amgStatic_answer".
 *
 * @property int $id
 * @property string $title
 * @property int $rank
 * @property int $trueImage
 * @property int $amgStatic_question_id
 *
 * @property AmgStaticQuestion $amgStaticQuestion
 */
class AmgStaticAnswer extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'amgStatic_answer';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rank', 'trueImage', 'amgStatic_question_id'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['amgStatic_question_id'], 'exist', 'skipOnError' => true, 'targetClass' => AmgStaticQuestion::className(), 'targetAttribute' => ['amgStatic_question_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Ответ',
            'rank' => 'Сортировка',
            'trueImage' => 'Соотверствие картинке',
            'amgStatic_question_id' => 'Amg Static Question ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAmgStaticQuestion()
    {
        return $this->hasOne(AmgStaticQuestion::className(), ['id' => 'amgStatic_question_id']);
    }

    public function beforeDelete()
    {
        $this->amgStaticQuestion->answerCount = --$this->amgStaticQuestion->answerCount;
        $this->amgStaticQuestion->save();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
