<?php

namespace common\models;

use common\models\ImageUpload;
use Yii;
use zxbodya\yii2\galleryManager\GalleryBehavior;
use common\behavior\RankGalleryBehavior;

/**
 * This is the model class for table "mixStatic".
 *
 * @property int $id
 * @property string $title
 * @property string $image
 * @property int $rank
 *
 * @property GalleryImage[] $galleryImages
 * @property MixStaticUser[] $mixStaticUsers
 * @property User[] $users
 */
class MixStatic extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mixStatic';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rank'], 'integer'],
            [['title', 'image'], 'string', 'max' => 255],
        ];
    }

    public function behaviors()
    {
        return [
            'galleryBehavior' => [
                'class' => RankGalleryBehavior::className(),
                'type' => 'mix-static',
                'extension' => 'jpg',
                'directory' => Yii::getAlias('@uploads') . '/images/gallery',
                'url' => '/uploads/images/gallery',
                'versions' => [
                    'small' => function ($img) {
                        /** @var \Imagine\Image\ImageInterface $img */
                        return $img
                            ->copy()
                            ->thumbnail(new \Imagine\Image\Box(303, 303));
                    },
                    'medium' => function ($img) {
                        /** @var Imagine\Image\ImageInterface $img */
                        $dstSize = $img->getSize();
                        $maxWidth = 800;
                        if ($dstSize->getWidth() > $maxWidth) {
                            $dstSize = $dstSize->widen($maxWidth);
                        }
                        return $img
                            ->copy()
                            ->resize($dstSize);
                    },
                ]
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'image' => 'Изображение',
            'rank' => 'Сортировака',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGalleryImages()
    {
        return $this->hasMany(GalleryImage::className(), ['ownerId' => 'id']);
    }

    public function savePhoto($fileName)
    {
        $this->image = $fileName;
        return $this->save(false);
    }

    public function getPhoto()
    {
        return ($this->image) ? '/uploads/images/' . $this->image : '/no_image.jpg';
    }

    public function getThumbPhoto()
    {
        return ($this->image) ? '/uploads/images/' . 'thumb_' . $this->image : '/no_image.jpg';
    }

    public function deletePhoto()
    {
        $imageUploadModel = new ImageUpload();

        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deletePhoto();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMixStaticUsers()
    {
        return $this->hasMany(MixStaticUser::className(), ['mixStatic_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->viaTable('mixStatic_user', ['mixStatic_id' => 'id']);
    }
}
