<?php

namespace common\models;

use common\behavior\RankGalleryBehavior;
use Imagine\Image\ImageInterface;
use Yii;

/**
 * This is the model class for table "photoReport".
 *
 * @property int $id
 * @property string $title
 * @property string $video
 * @property string $videoTitle
 * @property int $isVideoLoad
 *
 * @property PhotoReportGallery[] $photoReportGalleries
 */
class PhotoReport extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'photoReport';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['video'], 'string'],
            [['isVideoLoad'], 'integer'],
            [['title', 'videoTitle'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'galleryBehavior' => [
                'class' => RankGalleryBehavior::className(),
                'type' => 'photo-report',
                'extension' => 'jpg',
                'directory' => Yii::getAlias('@uploads') . '/images/photo-report-gallery',
                'url' => '/uploads/images/photo-report-gallery',
                'tableName' => 'photoReport_gallery',
                'versions' => [
                    'small' => function ($img) {
                        /** @var \Imagine\Image\ImageInterface $img */
                        return $img
                            ->copy()
                            ->thumbnail(new \Imagine\Image\Box(303, 303));
                    },
                    'medium' => function ($img) {
                        /** @var ImageInterface $img */
                        $dstSize = $img->getSize();
                        $maxWidth = 800;
                        if ($dstSize->getWidth() > $maxWidth) {
                            $dstSize = $dstSize->widen($maxWidth);
                        }
                        return $img
                            ->copy()
                            ->resize($dstSize);
                    },
                ]
            ]
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'video' => 'Видео',
            'videoTitle' => 'Заголовок для видео',
            'isVideoLoad' => 'Is Video Load',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhotoReportGalleries()
    {
        return $this->hasMany(PhotoReportGallery::className(), ['ownerId' => 'id']);
    }

    /**
     * @param $fileName
     * @param null $title
     * @return bool
     */
    public function saveVideo($fileName = null , $title = null)
    {
        if ($fileName !== null ){
            $this->video = $fileName;
        }
        if ($title !== null){
            $this->videoTitle = $title;
        }
        $this->isVideoLoad = 1;
        return $this->save(false);
    }

    /**
     * @return string
     */
    public function getVideo()
    {
        return ($this->video) ? '/uploads/videos/' . $this->video : '/no_video.jpg';
    }

    public function deleteVideo()
    {
        $imageUploadModel = new VideoUpload();

        $imageUploadModel->deleteCurrentVideo($this->video, ['gif', 'mp4', 'webm']);
    }

    public function beforeDelete()
    {
        $this->deleteVideo();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
